spring:
  profiles.active: h2
  main.banner-mode: 'off'
  h2.console.enabled: true
  http:
      multipart:
        max-file-size: 1000KB
        max-request-size: 1000KB

server.port: 8082

---
spring:
  profiles: h2, db_log

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate.jdbc.use_get_generated_keys: true
      javax.persistence.validation.mode: none
  datasource:
    data: classpath:/init.sql

---
spring:
  profiles: db_log
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type: trace

  loggin:
    level:
      org:
        hibernate:
          type: trace